apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Mi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: pvc-1
    namespace: default
  hostPath:
    path: /opt/data
    type: ""
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
       storage: 10Mi
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: use-pvc-1
  name: use-pvc-1
spec:
  containers:
  - image: nginx
    name: use-pvc-1
    volumeMounts:
    - mountPath: "/mnt"
      name: use-pvc-1
  volumes:
    - name: use-pvc-1
      persistentVolumeClaim:
        claimName: pvc-1
  restartPolicy: Never
