apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
  restartPolicy: Always
  tolerations:
  - key: "env"
    operator: "Equal"
    value: "development"
    effect: "NoSchedule"
