apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config
data:
  TEST_ENV: test

---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  restartPolicy: Never
  containers:
  - name: busybox
    image: registry.k8s.io/busybox
    command: [ "env" ]
    envFrom:
    - configMapRef:
        name: test-config