apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: default
type: Opaque
data:
  username: "YWRtaW4K"
  password: "cGFzc3dvcmQK"

---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: test-container
      image: registry.k8s.io/busybox
      command: [ "env" ]
      envFrom:
        - secretRef:
            name: secret
  restartPolicy: Never