apiVersion: v1
kind: Pod
metadata:
  labels:
    run: sample-app
    app: sample-app
  name: sample-app
spec:
  containers:
  - image: nginx
    name: sample-app
  dnsPolicy: ClusterFirst
  restartPolicy: Always
