apiVersion: v1
kind: Namespace
metadata:
  name: quota
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
  namespace: quota
spec:
  hard:
    requests.cpu: 1000m
    requests.memory: 1Gi
    limits.cpu: 1000m
    limits.memory: 1Gi
---
