apiVersion: v1
kind: Pod
metadata:
  name: quota-mem-cpu-demo
  namespace: quota-mem-cpu-example
spec:
  containers:
  - name: quota-mem-cpu-demo-ctr
    image: nginx
    resources:
      limits:
        memory: "800Mi"
        cpu: "800m"
      requests:
        memory: "600Mi"
        cpu: "400m"
---
# apiVersion: v1
# kind: Pod
# metadata:
#   name: quota-mem-cpu-demo-2
#   namespace: quota-mem-cpu-example
# spec:
#   containers:
#   - name: quota-mem-cpu-demo-2-ctr
#     image: redis
#     resources:
#       limits:
#         memory: "1Gi"
#         cpu: "800m"
#       requests:
#         memory: "700Mi"
#         cpu: "400m"
