apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: quota
spec:
  containers:
  - name: pod1
    image: nginx
    resources:
      requests:
        cpu: "500m"
        memory: "500Mi"
      limits:
        cpu: "500m"
        memory: "500Mi"
