apiVersion: v1
kind: Pod
metadata:
  name: pod2
  namespace: quota
spec:
  containers:
  - name: pod2
    image: nginx
    resources:
      requests:
        cpu: "1000m"
        memory: "1Gi"
      limits:
        cpu: "1000m"
        memory: "1Gi"
