apiVersion: v1
kind: ResourceQuota
metadata:
  name: pod-demo
  namespace: quota-pod-example
spec:
  hard:
    pods: "2"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-demo
  namespace: quota-mem-cpu-example
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
