apiVersion: v1
kind: Pod
metadata:
  name: envvars-secrets
spec:
  containers:
    - name: test
      image: nginx
      env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: user-pass
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: user-pass
              key: password
