apiVersion: v1
kind: Pod
metadata:
  labels:
    run: multi-pod
  name: multi-pod
spec:
  containers:
  - name: alpha
    image: nginx
    env:
    - name: name
      value: alpha
  - args:
    - sleep
    - "4800"
    image: busybox
    name: beta
    env:
    - name: name
      value: beta
