apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx2
  name: nginx2
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
              - key: disktype
                operator: In
                values:
                - ssd
  containers:
  - image: nginx
    name: nginx2
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
