apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
            - key: disktype
              operator: In
              values:
              - ssd
  containers:
  - image: nginx
    name: nginx
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
